from __future__ import annotations

import csv
import json
from datetime import UTC, datetime
from pathlib import Path

from .constants import LANGUAGES
from .evaluation import evaluate_submission
from .submissions import load_metadata

FIELDS = [
    "rank", "team", "slug", "score", "speed_chars_per_second", "vocab_size", "status",
    "evaluated_at", *[f"{language}_normalized" for language in LANGUAGES],
]


def build_leaderboard(
    submissions_dir: str | Path,
    evaluation_data: str | Path,
    baseline_stats: str | Path,
    *,
    benchmark_repeats: int = 3,
    final_only: bool = False,
) -> tuple[list[dict], list[dict]]:
    submissions_dir = Path(submissions_dir)
    rows: list[dict] = []
    failures: list[dict] = []
    evaluated_at = datetime.now(UTC).replace(microsecond=0).isoformat()
    for directory in sorted(submissions_dir.iterdir() if submissions_dir.exists() else []):
        if not directory.is_dir():
            continue
        try:
            if final_only and directory.name != "baseline":
                metadata = load_metadata(directory / "metadata.yml")
                if not metadata.final:
                    continue
            result = evaluate_submission(
                directory,
                evaluation_data,
                baseline_stats,
                benchmark_repeats=benchmark_repeats,
            )
            rows.append({
                "team": result["team"],
                "slug": result["slug"],
                "score": result["score"],
                "speed_chars_per_second": result["throughput"],
                "vocab_size": result["vocab_size"],
                "status": "baseline" if result["slug"] == "baseline" else "ranked",
                "evaluated_at": evaluated_at,
                **{
                    f"{language}_normalized": result["normalized"][language]
                    for language in LANGUAGES
                },
            })
        except Exception as exc:
            failures.append({"slug": directory.name, "error": str(exc)})

    competitors = sorted(
        (row for row in rows if row["status"] == "ranked"),
        key=lambda row: (row["score"], -row["speed_chars_per_second"], row["team"].casefold()),
    )
    for rank, row in enumerate(competitors, start=1):
        row["rank"] = rank
    baselines = [row for row in rows if row["status"] == "baseline"]
    for row in baselines:
        row["rank"] = "—"
    return competitors + baselines, failures


def write_leaderboard(rows: list[dict], csv_path: str | Path, markdown_path: str | Path) -> None:
    csv_path = Path(csv_path)
    markdown_path = Path(markdown_path)
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)
    with csv_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: _csv_value(row.get(field, "")) for field in FIELDS})

    lines = [
        "# 🏆 Leaderboard",
        "",
        "Lower score is better. Speed is informational; official ranking uses score only.",
        "",
        "| Rank | Team | Score ↓ | Speed ↑ | Vocabulary |",
        "| ---: | :--- | ---: | ---: | ---: |",
    ]
    for row in rows:
        speed = f"{row['speed_chars_per_second'] / 1_000_000:.2f}M chars/s"
        team = str(row["team"]).replace("|", "\\|")
        label = f"{team} (baseline)" if row["status"] == "baseline" else team
        lines.append(
            f"| {row['rank']} | {label} | {row['score']:.4f} | {speed} | {row['vocab_size']:,} |"
        )
    lines.extend(["", "Generated by `scripts/update_leaderboard.py`.", ""])
    markdown_path.write_text("\n".join(lines), encoding="utf-8")


def write_site_json(rows: list[dict], path: str | Path) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "updated_at": rows[0]["evaluated_at"] if rows else None,
        "entries": rows,
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _csv_value(value):
    if isinstance(value, float):
        return f"{value:.8f}"
    return value
